name: Notify clients of a release
run-name: 📣 Notify clients of ${{ github.event.release.tag_name }}
on:
  release:
    types: [published]
permissions:
  contents: read
env:
  ORCHESTRA_MODULE_RELEASE_PIPELINE_ID: 35a8e336-d557-4e36-aed5-3e3d42f1a411
jobs:
  notify:
    name: Trigger client notification
    runs-on: blacksmith-2vcpu-ubuntu-2404-arm
    timeout-minutes: 15
    steps:
      - name: Trigger Orchestra notification pipeline
        uses: orchestra-hq/run-pipeline@v1
        with:
          api_key: ${{ secrets.ORCHESTRA_API_TOKEN }}
          pipeline_id: ${{ env.ORCHESTRA_MODULE_RELEASE_PIPELINE_ID }}
          run_inputs: '{"repository": ${{ toJSON(github.repository) }}, "module_version": ${{ toJSON(github.event.release.tag_name) }}}'
